export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

export const ITEMS_REQUESTED = 'ITEMS_REQUESTED';
export const ITEMS_REQUEST_SUCCESS = 'ITEMS_REQUEST_SUCCESS';
export const ITEMS_REQUEST_FAILURE = 'ITEMS_REQUEST_FAILURE';

export const ON_ITEM_DELETE_REQUEST = 'ON_ITEM_DELETE_REQUEST';
export const ON_ITEM_UPDATE_REQUEST = 'ON_ITEM_UPDATE_REQUEST';